=== rad55RUS/ProjectSugarUnicorn/Assets/Data/Data_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Year" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CPI" type="xs:double"/>
							<xs:element name="Population" type="xs:double"/>
							<xs:element name="District" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Population" type="xs:double"/>
									</xs:sequence>
									<xs:attribute name="Value" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Value" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rad55RUS/ProjectSugarUnicorn/Assets/Data/Data.xml
<?xml version="1.0" encoding="utf-8" ?>
<Data 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Data_Schema.xsd">
	<Year Value="2008">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2009">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2010">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2011">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2012">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2013">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2014">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2015">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2016">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2017">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2018">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2019">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2020">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2021">
		<CPI>102.31</CPI>
	</Year>
	<Year Value="2022">
		<CPI>102.31</CPI>
	</Year>
</Data>
