=== rad55RUS/ProjectSugarUnicorn/Assets/Data/InflationData_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="InflationData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Inflation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CPI" type="xs:double"/>
						</xs:sequence>
						<xs:attribute name="Year" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rad55RUS/ProjectSugarUnicorn/Assets/Data/InflationData.xml
<?xml version="1.0" encoding="utf-8" ?>
<InflationData 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InflationData_Schema.xsd">
	<Inflation Year="2008">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2009">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2010">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2011">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2012">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2013">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2014">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2015">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2016">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2017">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2018">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2019">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2020">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2021">
		<CPI>102.31</CPI>
	</Inflation>
	<Inflation Year="2022">
		<CPI>102.31</CPI>
	</Inflation>
</InflationData>
